// R11/G5: only the external LLM is scripted. Docker, Harness, MCP tools, Git,
// JsonTaskStateStore, MessageBus/SSE, and orchestration are all real.
import { existsSync, readFileSync } from 'node:fs';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { Dockerode } from '@agora/runtime-sandbox';
import { CallId, type GenerateOptions, LlmAdapter, type StreamChunk } from '@deepseek-ai/dsh-llm';
import { afterEach, describe, expect, it } from 'vitest';

import { ChannelStream } from '../src/server/channel-stream';
import { createMessageRuntime } from '../src/server/message-runtime';
import { createWebTaskCompositionFactory } from '../src/server/task-composition';
import { TaskOrchestrationRuntime } from '../src/server/task-orchestration-runtime';

const sockets = [
  process.env.DOCKER_HOST,
  '/var/run/docker.sock',
  join(process.env.HOME ?? '', '.docker/run/docker.sock'),
].filter((socket): socket is string => Boolean(socket));

function connectDocker(): Dockerode | null {
  for (const socket of sockets) {
    if (socket.startsWith('unix://') || socket.startsWith('http://')) return new Dockerode();
    if (existsSync(socket)) return new Dockerode({ socketPath: socket });
  }
  return null;
}

const docker = connectDocker();
const describeDocker = docker === null ? describe.skip : describe;
const roots: string[] = [];

const CACHE_SOURCE = `class TtlLruCache {
  constructor(capacity, now = () => Date.now()) {
    this.capacity = capacity;
    this.now = now;
    this.items = new Map();
  }
  set(key, value, ttlMs) {
    this.items.delete(key);
    this.items.set(key, { value, expiresAt: this.now() + ttlMs });
    while (this.items.size > this.capacity) this.items.delete(this.items.keys().next().value);
  }
  get(key) {
    const entry = this.items.get(key);
    if (!entry) return undefined;
    if (entry.expiresAt <= this.now()) { this.items.delete(key); return undefined; }
    this.items.delete(key);
    this.items.set(key, entry);
    return entry.value;
  }
}
module.exports = { TtlLruCache };
`;

const TEST_SOURCE = `const { test } = require('node:test');
const assert = require('node:assert/strict');
const { TtlLruCache } = require('./ttl-lru.js');
test('returns stored values', () => { const c = new TtlLruCache(2); c.set('a', 1, 1000); assert.equal(c.get('a'), 1); });
test('evicts the least recently used value', () => { const c = new TtlLruCache(2); c.set('a', 1, 1000); c.set('b', 2, 1000); c.get('a'); c.set('c', 3, 1000); assert.equal(c.get('b'), undefined); });
test('expires values by ttl', () => { let now = 0; const c = new TtlLruCache(2, () => now); c.set('a', 1, 10); now = 10; assert.equal(c.get('a'), undefined); });
`;

const PATCH = [
  'diff --git a/README.md b/README.md',
  'new file mode 100644',
  '--- /dev/null',
  '+++ b/README.md',
  '@@ -0,0 +1 @@',
  '+TTL-aware LRU cache generated by Agora.',
  '',
].join('\n');

interface Action {
  tool: 'fs_write' | 'sandbox_run' | 'git_applyPatch' | 'git_diff' | 'fs_read' | 'lint_check';
  args: Record<string, unknown>;
}

const actions: Readonly<Record<string, readonly Action[]>> = {
  CODER: [
    { tool: 'fs_write', args: { path: 'ttl-lru.js', content: CACHE_SOURCE } },
    { tool: 'git_applyPatch', args: { patch: PATCH } },
  ],
  TESTER: [
    { tool: 'fs_write', args: { path: 'ttl-lru.test.js', content: TEST_SOURCE } },
    { tool: 'sandbox_run', args: { cmd: 'node --test ttl-lru.test.js' } },
    {
      tool: 'fs_write',
      args: {
        path: 'test-results.json',
        content: JSON.stringify({ passed: true, total: 3, failed: 0, failures: [] }),
      },
    },
  ],
  REVIEWER: [
    { tool: 'git_diff', args: { ref: 'HEAD~1' } },
    { tool: 'fs_read', args: { path: 'ttl-lru.js' } },
    { tool: 'lint_check', args: { paths: ['ttl-lru.js'] } },
  ],
};

const finalText: Readonly<Record<string, string>> = {
  CODER: 'Implemented and committed the TTL-aware LRU cache.',
  TESTER: 'All three cache tests passed.',
  REVIEWER: JSON.stringify([
    {
      id: 'docker-review-approved',
      kind: 'verdict',
      verdict: 'approved',
      summary: 'The implementation and real test run satisfy the goal.',
    },
  ]),
};

class ScriptedAdapter extends LlmAdapter {
  private sequence = 0;

  async *stream(options: GenerateOptions): AsyncIterable<StreamChunk> {
    const role = projectionRole(options);
    const completed = options.messages.reduce(
      (count, message) =>
        count + message.content.filter((block) => block.type === 'tool-result').length,
      0,
    );
    const action = actions[role]?.[completed];
    if (action === undefined) {
      yield* textChunks(finalText[role] ?? 'done');
      return;
    }
    yield* toolChunks(action, CallId(`web-docker-${this.sequence++}`));
  }
}

function projectionRole(options: GenerateOptions): string {
  const first = options.messages[0];
  const text = first?.content.find((block) => block.type === 'text');
  if (text?.type !== 'text') throw new Error('expected projected role input');
  const parsed = JSON.parse(text.text) as { role?: unknown };
  if (typeof parsed.role !== 'string') throw new Error('expected projected role');
  return parsed.role;
}

function usage(): StreamChunk {
  return { type: 'usage', usage: { inputTokens: 8, outputTokens: 8 } };
}

function* toolChunks(action: Action, id: CallId): Iterable<StreamChunk> {
  const argumentsJson = JSON.stringify(action.args);
  yield { type: 'block-start', index: 0, blockType: 'tool-call' };
  yield { type: 'tool-call-delta', index: 0, id, name: action.tool, argumentsDelta: argumentsJson };
  yield {
    type: 'block-end',
    index: 0,
    block: { type: 'tool-call', id, name: action.tool, arguments: argumentsJson },
  };
  yield usage();
  yield { type: 'finish', reason: { kind: 'stop' } };
}

function* textChunks(text: string): Iterable<StreamChunk> {
  yield { type: 'block-start', index: 0, blockType: 'text' };
  yield { type: 'text-delta', index: 0, text };
  yield { type: 'block-end', index: 0, block: { type: 'text', text } };
  yield usage();
  yield { type: 'finish', reason: { kind: 'stop' } };
}

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

describeDocker('Web orchestration bridge (G5 real Docker/Harness/MCP chain)', () => {
  it('persists and streams one continuous cache task through Coder, Tester, and Reviewer', async () => {
    const root = await mkdtemp(join(tmpdir(), 'agora-web-docker-g5-'));
    roots.push(root);
    const messages = createMessageRuntime(root, new ChannelStream());
    const runtime = new TaskOrchestrationRuntime(
      messages,
      createWebTaskCompositionFactory({
        sandboxConfig: { kind: 'docker', ...(docker === null ? {} : { docker }) },
        executorOptions: { adapter: new ScriptedAdapter(), provider: 'agora-web-g5' },
      }),
    );

    const started = await runtime.start({
      projectId: 'demo',
      taskId: 'ttl-lru-g5',
      requestId: 'g5-request',
      goal: '实现 TTL LRU 缓存',
    });
    expect(started.startOutcome).toBe('started');
    await runtime.waitForIdle({ projectId: 'demo', taskId: 'ttl-lru-g5' });
    const summary = await runtime.summary({ projectId: 'demo', taskId: 'ttl-lru-g5' });

    expect(summary).toMatchObject({ runStatus: 'completed', phase: 'done' });
    expect(summary?.testResults).toMatchObject({ passed: true, total: 3 });
    expect(summary?.artifactPath).toBeTruthy();
    expect(readFileSync(join(summary?.artifactPath ?? '', 'ttl-lru.js'), 'utf8')).toContain(
      'class TtlLruCache',
    );
    const state = await messages.store.load({ projectId: 'demo', taskId: 'ttl-lru-g5' });
    expect(state?.messages.some((message) => message.fromRole === 'CODER')).toBe(true);
    expect(state?.messages.some((message) => message.fromRole === 'TESTER')).toBe(true);
    expect(state?.messages.some((message) => message.fromRole === 'REVIEWER')).toBe(true);
    await runtime.disposeAll();
  }, 120_000);
});
